# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/

# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice

# The `service` block is the name of the service
service: dcm-requirements

# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1
  environment:
    REQUIREMENTS_TABLE: dcm_requirements_${opt:stage, self:provider.stage}

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 'arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.REQUIREMENTS_TABLE}'

# The `functions` block defines what code to deploy
functions:
  createClanRequirement:
    handler: handler.createClanRequirement
    events:
      - http:
          path: requirement
          method: post
          cors: true

  getClanRequirements:
    handler: handler.getClanRequirements
    events:
      - http:
          path: requirement
          method: get
          request:
            parameters:
              querystrings:
                clanId: true

resources:
  Resources:
    DestinyClanManagerRequirementTable:
      Type: AWS::DynamoDB::Table
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S

          - AttributeName: clanId
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH

          - AttributeName: clanId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.REQUIREMENTS_TABLE}
